<a href="https://colab.research.google.com/github/RonGarcia-hub/CPE311-CPE22S3/blob/main/Garcia%2C_Ron_Seatwork_7_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Using the meteorite data from the Meteorite_Landings.csv file, update the year column to only contain the year, convert it to a numeric data type, and create a new column indicating whether the meteorite was observed falling before 1970. Set the index to the id column and extract all the rows with IDs between 10,036 and 10,040 (inclusive) with loc[].


Hint 1: Use year.str.slice() to grab a substring.

Hint 2: Make sure to sort the index before using loc[] to select the range.


Bonus: There's a data entry error in the year column. Can you find it? (Don't spend too much time on this.)

In [2]:
import pandas as pd

In [3]:
#csv has been loaded
df = pd.read_csv('Meteorite_Landings.csv')
df.head(11)

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"
5,Adhi Kot,379,Valid,EH4,4239.0,Fell,01/01/1919 12:00:00 AM,32.10000,71.80000,"(32.1, 71.8)"
6,Adzhi-Bogdo (stone),390,Valid,LL3-6,910.0,Fell,01/01/1949 12:00:00 AM,44.83333,95.16667,"(44.83333, 95.16667)"
7,Agen,392,Valid,H5,30000.0,Fell,01/01/1814 12:00:00 AM,44.21667,0.61667,"(44.21667, 0.61667)"
8,Aguada,398,Valid,L6,1620.0,Fell,01/01/1930 12:00:00 AM,-31.60000,-65.23333,"(-31.6, -65.23333)"
9,Aguila Blanca,417,Valid,L,1440.0,Fell,01/01/1920 12:00:00 AM,-30.86667,-64.55000,"(-30.86667, -64.55)"
10,Aioun el Atrouss,423,Valid,Diogenite-pm,1000.0,Fell,01/01/1974 12:00:00 AM,16.39806,-9.57028,"(16.39806, -9.57028)"

In [4]:
#update the year column to only contain the year

df['year'] = pd.to_datetime(df['year'])
df['year'] = df['year'].dt.year

df.head(11)

/tmp/ipython-input-2953333037.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['year'] = pd.to_datetime(df['year'], errors='coerce')

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,1880,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,1951,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,1952,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,1976,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,1902,-33.16667,-64.95000,"(-33.16667, -64.95)"
5,Adhi Kot,379,Valid,EH4,4239.0,Fell,1919,32.10000,71.80000,"(32.1, 71.8)"
6,Adzhi-Bogdo (stone),390,Valid,LL3-6,910.0,Fell,1949,44.83333,95.16667,"(44.83333, 95.16667)"
7,Agen,392,Valid,H5,30000.0,Fell,1814,44.21667,0.61667,"(44.21667, 0.61667)"
8,Aguada,398,Valid,L6,1620.0,Fell,1930,-31.60000,-65.23333,"(-31.6, -65.23333)"
9,Aguila Blanca,417,Valid,L,1440.0,Fell,1920,-30.86667,-64.55000,"(-30.86667, -64.55)"
10,Aioun el Atrouss,423,Valid,Diogenite-pm,1000.0,Fell,1974,16.39806,-9.57028,"(16.39806, -9.57028)"

In [5]:
# convert it to a numeric data type
df['year'].dtype

#didn't do anything :P

Int64Dtype()

In [6]:
#create a new column indicating whether the meteorite was observed falling before 1970.

df['before_1970'] = df['year'] < 1970
df.head(16)

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation,before_1970
0,Aachen,1,Valid,L5,21.0,Fell,1880,50.77500,6.08333,"(50.775, 6.08333)",True
1,Aarhus,2,Valid,H6,720.0,Fell,1951,56.18333,10.23333,"(56.18333, 10.23333)",True
2,Abee,6,Valid,EH4,107000.0,Fell,1952,54.21667,-113.00000,"(54.21667, -113.0)",True
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,1976,16.88333,-99.90000,"(16.88333, -99.9)",False
4,Achiras,370,Valid,L6,780.0,Fell,1902,-33.16667,-64.95000,"(-33.16667, -64.95)",True
5,Adhi Kot,379,Valid,EH4,4239.0,Fell,1919,32.10000,71.80000,"(32.1, 71.8)",True
6,Adzhi-Bogdo (stone),390,Valid,LL3-6,910.0,Fell,1949,44.83333,95.16667,"(44.83333, 95.16667)",True
7,Agen,392,Valid,H5,30000.0,Fell,1814,44.21667,0.61667,"(44.21667, 0.61667)",True
8,Aguada,398,Valid,L6,1620.0,Fell,1930,-31.60000,-65.23333,"(-31.6, -65.23333)",True
9,Aguila Blanca,417,Valid,L,1440.0,Fell,1920,-30.86667,-64.55000,"(-30.86667, -64.55)",True
10,Aioun el Atrouss,423,Valid,Diogenite-pm,1000.0,Fell,1974,16.39806,-9.57028,"(16.39806, -9.57028)",False
11,Aïr,424,Valid,L6,24000.0,Fell,1925,19.08333,8.38333,"(19.08333, 8.38333)",True
12,Aire-sur-la-Lys,425,Valid,Unknown,NaN,Fell,1769,50.66667,2.33333,"(50.66667, 2.33333)",True
13,Akaba,426,Valid,L6,779.0,Fell,1949,29.51667,35.05000,"(29.51667, 35.05)",True
14,Akbarpur,427,Valid,H4,1800.0,Fell,1838,29.71667,77.95000,"(29.71667, 77.95)",True
15,Akwanga,432,Valid,H,3000.0,Fell,1959,8.91667,8.43333,"(8.91667, 8.43333)",True

In [15]:
#Set the index to the id column and extract all the rows with IDs between 10,036 and 10,040 (inclusive) with loc[].

df = df.set_index('id')
df = df.sort_index()
sortedId = df.loc[10036:10040]
sortedId

#bonus - the year where id 10039 is NA

,name,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation,before_1970
id,,,,,,,,,,
10036,Enigma,Valid,H4,94.0,Found,1967,31.33333,-82.31667,"(31.33333, -82.31667)",True
10037,Enon,Valid,"Iron, ungrouped",763.0,Found,1883,39.86667,-83.95000,"(39.86667, -83.95)",True
10038,Enshi,Valid,H5,8000.0,Fell,1974,30.30000,109.50000,"(30.3, 109.5)",False
10039,Ensisheim,Valid,LL6,127000.0,Fell,<NA>,47.86667,7.35000,"(47.86667, 7.35)",<NA>