<a href="https://colab.research.google.com/github/RonGarcia-hub/CPE311-CPE22S3/blob/main/Garcia_HOA_7_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Module 7 : Data wrangling with Pandas

# CPE311 Computational Thinking with Python

Submitted by: Garcia, Ron Allen P.

Performed on: 2/24/26

Submitted on: 2/24/26

Submitted to: Engr. Neal Barton James Matira

#7.1 Supplementary Activity
We want to look at data for the Facebook, Apple, Amazon, Netflix, and Google (FAANG) stocks, but we were given each as a separate CSV file. Combine them into a single file and store the dataframe of the FAANG data as faang for the rest of the exercises:

Exercise 1

1.Read each file in.

2.Add a column to each dataframe, called ticker, indicating the ticker symbol it is for (Apple's is AAPL, for example). This is how you look up a stock. Each file's name is also the ticker symbol, so be sure to capitalize it.

3.Append them together into a single dataframe.

4.Save the result in a CSV file called faang.csv.

In [8]:
pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->bs4) (4.15.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2

In [11]:
#Exercise 1.1

import pandas as pd

df_aapl = pd.read_csv('aapl.csv')
df_amzn = pd.read_csv('amzn.csv')
df_fb = pd.read_csv('fb.csv')
df_goog = pd.read_csv('goog.csv')
df_nflx = pd.read_csv('nflx.csv')

         date      open      high       low     close    volume
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766

In [16]:
#Exercise 1.2

df_aapl['Ticker'] = "AAPL"
df_amzn['Ticker'] = "AMZN"
df_fb['Ticker'] = "FB"
df_goog['Ticker'] = "GOOG"
df_nflx['Ticker'] = "NFLX"

         date    open    high       low   close    volume Ticker
0  2018-01-02  196.10  201.65  195.4200  201.07  10966889   NFLX
1  2018-01-03  202.05  206.21  201.5000  205.05   8591369   NFLX
2  2018-01-04  206.20  207.05  204.0006  205.63   6029616   NFLX
3  2018-01-05  207.25  210.02  205.5900  209.99   7033240   NFLX
4  2018-01-08  210.02  212.50  208.4400  212.05   5580178   NFLX

In [19]:
#Exercise 1.3

dfs_list = [df_aapl, df_amzn, df_fb, df_goog, df_nflx]
df_faang = pd.concat(dfs_list)

           date       open       high        low      close    volume Ticker
0    2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
1    2018-01-03   169.2521   171.2337   168.6929   168.9578  29517899   AAPL
2    2018-01-04   169.2619   170.1742   168.8106   169.7426  22434597   AAPL
3    2018-01-05   170.1448   172.0381   169.7622   171.6751  23660018   AAPL
4    2018-01-08   171.0375   172.2736   170.6255   171.0375  20567766   AAPL
..          ...        ...        ...        ...        ...       ...    ...
244  2018-12-20  1484.0000  1509.5000  1432.6900  1460.8300   9991833   AMZN
245  2018-12-21  1464.9900  1480.0000  1363.9600  1377.4500  13640320   AMZN
246  2018-12-24  1346.0000  1396.0300  1307.0000  1343.9600   7219996   AMZN
247  2018-12-26  1368.8900  1473.1600  1363.0100  1470.9000  10411801   AMZN
248  2018-12-27  1454.2000  1469.0000  1390.3100  1461.6400   9722034   AMZN

[500 rows x 7 columns]

In [20]:
#Exercise 1.4

df_faang.to_csv('faang.csv', index=False)

##Exercise 2

1.With faang, use type conversion to change the date column into a datetime and the volume column into integers. Then, sort by date and ticker.

2.Find the seven rows with the highest value for volume.

3.Right now, the data is somewhere between long and wide format. Use melt() to make it completely long format. Hint: date and ticker are our ID variables (they uniquely identify each row). We need to melt the rest so that we don't have separate columns for open, high, low, close, and volume.

In [23]:
#Exercise 2.1

from datetime import date, datetime, time


df_faang["date"] = pd.to_datetime(df_faang["date"])


df_faang["volume"] = df_faang["volume"].astype("int64")


df_faang = df_faang.sort_values(by=["date", "Ticker"])

df_faang.head(11)

        date       open       high        low      close    volume Ticker
0 2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
0 2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
0 2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
0 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
0 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX
1 2018-01-03   169.2521   171.2337   168.6929   168.9578  29517899   AAPL
1 2018-01-03  1188.3000  1205.4900  1188.3000  1204.2000   3108793   AMZN
1 2018-01-03   181.8800   184.7800   181.3300   184.6700  16886563     FB
1 2018-01-03  1064.3100  1086.2900  1063.2100  1082.4800   1430170   GOOG
1 2018-01-03   202.0500   206.2100   201.5000   205.0500   8591369   NFLX
2 2018-01-04   169.2619   170.1742   168.8106   169.7426  22434597   AAPL

In [24]:
#Exercise 2.2

df_faang.nlargest(7, "volume")

          date      open      high       low     close     volume Ticker
142 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
53  2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
57  2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
54  2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [25]:
df_faang.melt()

     variable                value
0        date  2018-01-02 00:00:00
1        date  2018-01-02 00:00:00
2        date  2018-01-02 00:00:00
3        date  2018-01-02 00:00:00
4        date  2018-01-02 00:00:00
...       ...                  ...
8780   Ticker                 AAPL
8781   Ticker                 AMZN
8782   Ticker                   FB
8783   Ticker                 GOOG
8784   Ticker                 NFLX

[8785 rows x 2 columns]

## Exercise 3

1.Using web scraping, search for the list of the hospitals, their address and contact information. Save the list in a new csv file, hospitals.csv.

2.Using the generated hospitals.csv, convert the csv file into pandas dataframe. Prepare the data using the necessary preprocessing techniques.

In [33]:
import selenium

ModuleNotFoundError: No module named 'selenium'

In [32]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

driver = webdriver.Chrome()
driver.get("https://www.yelp.com/search?cflt=hospitals&find_loc=Quezon+City%2C+Metro+Manila")

time.sleep(5)

print(driver.page_source)
driver.quit()

ModuleNotFoundError: No module named 'selenium'

In [29]:
soup  = BeautifulSoup(response.text, 'html.parser')

NameError: name 'response' is not defined

In [28]:
import requests
from bs4 import BeautifulSoup

data = soup.find(class_='list__09f24__gE1oR')
print(data.prettify())

NameError: name 'soup' is not defined

##Conlcusion

In this activity I have conlcuded that dataframe manipulation is a good skill to hone alongside web scraping, being able to process the data that is gathered is useful and it helps a lot if youre are able to visualize the data gathered in order for other people to understand it better.